# Generated by Django 4.2.4 on 2024-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_questions_type_questions_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=2)),
                ('difficulty', models.IntegerField()),
                ('noofqn', models.IntegerField()),
            ],
        ),
    ]
