# Generated by Django 4.2.4 on 2024-01-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='partA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('noofqns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='partB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('noofqns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='partC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('noofqns', models.IntegerField()),
            ],
        ),
    ]
