# Generated by Django 4.2.4 on 2024-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_parta_partb_partc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parta',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='parta',
            name='noofqns',
        ),
        migrations.RemoveField(
            model_name='partb',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='partb',
            name='noofqns',
        ),
        migrations.RemoveField(
            model_name='partc',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='partc',
            name='noofqns',
        ),
        migrations.AddField(
            model_name='parta',
            name='difficulty1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parta',
            name='difficulty2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parta',
            name='difficulty3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partb',
            name='difficulty1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partb',
            name='difficulty2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partb',
            name='difficulty3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partc',
            name='difficulty1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partc',
            name='difficulty2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partc',
            name='difficulty3',
            field=models.IntegerField(default=0),
        ),
    ]
