# Generated by Django 4.2.4 on 2024-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_parta_difficulty_remove_parta_noofqns_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customize',
        ),
        migrations.AlterField(
            model_name='parta',
            name='difficulty1',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='parta',
            name='difficulty2',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='parta',
            name='difficulty3',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='partb',
            name='difficulty1',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='partb',
            name='difficulty2',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='partb',
            name='difficulty3',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='partc',
            name='difficulty1',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='partc',
            name='difficulty2',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='partc',
            name='difficulty3',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
