# Generated by Django 4.2.4 on 2024-01-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='BT',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='questions',
            name='CO',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='questions',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='paper',
            field=models.CharField(default='', max_length=50),
        ),
    ]
