# Generated by Django 4.2.4 on 2024-01-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_questions_bt_questions_co_questions_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
