# Generated by Django 4.2.4 on 2024-01-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_questions_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='paper',
        ),
    ]
