# Generated by Django 4.2.4 on 2024-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_questions_frequency_remove_questions_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='topic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
