# Generated by Django 4.2.4 on 2024-02-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_department_semester_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
